baseURL: "https://penthaapatel.github.io/"
title: Penthaa Patel
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Home
                  weight: 1
                - name: About Me
                  url: about/
                  weight: 2
                - name: Projects
                  url: projects/
                  weight: 3
                - name: All Posts
                  url: posts/
                  weight: 4
                - name: Archives
                  url: archives
                  weight: 4
                - name: Search
                  url: search/
                  weight: 5
                - name: Tags
                  url: tags/
                  weight: 6
                # - name: Categories
                #   url: categories/
                #   weight: 7

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Penthaa Patel

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: false
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    TocOpen: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: true
        title: Penthaa Patel
        imageUrl: "me.jpg"
        imageTitle: my image
        imageWidth: 120
        imageHeight: 120
        subtitle: "Hi there! 👋 Follow along my programming journey here on my blog where I document everything I learn about tech."
        buttons:
            - name: All Posts
              url: posts
            - name: About Me
              url: about


    homeInfoParams:
        Title: "Hi There! 👋"
        Content: >
            Welcome to my blog.
    socialIcons:
        - name: github
          url: "https://github.com/penthaapatel"
        - name: linkedin
          url: "https://www.linkedin.com/in/penthaapatel/"
        - name: medium
          url: "https://penthaa.medium.com"
        - name: dev
          url: "https://dev.to/penthaapatel"

    # editPost:
    #     URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page
        responsiveImages: false

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true